---
title: "Clustering Lab"
author: "Brian Wright"
date: "9/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Goal: Know how to make decisions and answer questions using clustering. 

Repeat the clustering process only using the Rep house votes dataset
- What differences and similarities did you see between how the clustering 
worked for the datasets?

```{r, include=FALSE}
library(e1071)
library(tidyverse)
library(plotly)
library(htmltools)
library(devtools)
library(caret)
library(NbClust)
```

```{r}
#Load in Data
house_votes_Rep = read_csv("/Users/catherineschuster/Desktop/Fall 2021/DS 3001/DS-3001-Main/06_Clustering/house_votes_Rep.csv")

view(house_votes_Rep)

str(house_votes_Rep)

table(house_votes_Rep$party.labels)
```


```{r}
#Select the variables to be included in the cluster 
clust_data = house_votes_Rep[, c("aye", "nay", "other")]
```

```{r}
#Run the clustering algo with 2 centers
set.seed(17)
kmeans_rep = kmeans(clust_data, centers = 2, algorithm = "Lloyd")
```

```{r}
#View the results
View(kmeans_rep)
```

```{r}
#Visualize the output
party_clusters = as.factor(kmeans_rep$cluster)
ggplot(house_votes_Rep, aes(x = aye, 
                            y = nay,
                            color = party.labels,  #<- tell R how to color 
                            #   the data points
                            shape = party_clusters)) + 
  geom_point(size = 6) +
  ggtitle("Aye vs. Nay votes for Democrat-introduced bills") +
  xlab("Number of Aye Votes") +
  ylab("Number of Nay Votes") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster 1", "Cluster 2"),
                     values = c("1", "2")) +
  scale_color_manual(name = "Party",         #<- tell R which colors to use and
                     #   which labels to include in the legend
                     labels = c("Republican", "Democratic"),
                     values = c("red", "blue")) +
  theme_light()

```

```{r}
#Evaluate the quality of the clustering 
betweenss_rep = kmeans_rep$betweenss

# Total variance, "totss" is the sum of the distances between all the points in the data set.
totss_rep = kmeans_rep$totss

# Variance accounted for by clusters.
(var_exp_rep = betweenss_rep / totss_rep)
```

```{r}
#Use the function we created to evaluate several different number of clusters
explained_variance = function(data_in, k){
  
  # Running the kmeans algorithm.
  set.seed(1)
  kmeans_obj = kmeans(data_in, centers = k, algorithm = "Lloyd", iter.max = 30)
  
  # Variance accounted for by clusters:
  # var_exp = intercluster variance / total variance
  var_exp = kmeans_obj$betweenss / kmeans_obj$totss
  var_exp  
}

explained_var_rep = sapply(1:10, explained_variance, data_in = clust_data)
elbow_data_rep = data.frame(k = 1:10, explained_var_rep)


```

```{r}
#Create a elbow chart of the output 
ggplot(elbow_data_rep, 
       aes(x = k,  
           y = explained_var_rep)) + 
  geom_point(size = 4) +           #<- sets the size of the data points
  geom_line(size = 1) +            #<- sets the thickness of the line
  xlab('k') + 
  ylab('Inter-cluster Variance / Total Variance') + 
  theme_light()
```

```{r}
#Use NbClust to select a number of clusters
(nbclust_rep = NbClust(data = clust_data, method = "kmeans"))

# View the output of NbClust.
nbclust_rep

# View the output that shows the number of clusters each method recommends.
View(nbclust_rep$Best.nc)
```

```{r}
#Display the results visually 
freq_k_rep = nbclust_rep$Best.nc[1,]
freq_k_rep = data.frame(freq_k_rep)
View(freq_k_rep)

dev.off()

# Plot as a histogram.
ggplot(freq_k_rep,
       aes(x = freq_k_rep)) +
  geom_bar() +
  scale_x_continuous(breaks = seq(0, 15, by = 1)) +
  scale_y_continuous(breaks = seq(0, 12, by = 1)) +
  labs(x = "Number of Clusters",
       y = "Number of Votes",
       title = "Cluster Analysis")
```

```{r}
#Using the recommended number of cluster compare the quality of the model 
#with 2 clusters 

# Both NBclust and the elbow curve method recommended that the model be built with two clusters. Thus, # there is nothing to compare to. 

```


```{r}
#Bonus: Create a 3d version of the output
# We can visualize votes in 3D with the following code.
# View our data.
View(house_votes_Rep)

# Assign colors by party in a new data frame.
party_color3D_Rep = data.frame(party.labels = c("Democrat", "Republican"),
                               color = c("blue", "red"))

View(party_color3D_Rep)


# Join the new data frame to our house_votes_Dem data set.
house_votes_color_Rep = inner_join(house_votes_Rep, party_color3D_Rep)

house_votes_color_Rep$clusters <- (party_clusters)

str(house_votes_color_Rep)

house_votes_color_Rep$Last.Name <- gsub("[^[:alnum:]]", "", house_votes_color_Rep$Last.Name)

# Use plotly to do a 3d imaging 

fig <- plot_ly(house_votes_color_Rep, 
               type = "scatter3d",
               mode="markers",
               symbol = ~clusters,
               x = ~aye, 
               y = ~nay, 
               z = ~other,
               color = ~color,
               colors = c('#0C4B8E','#BF382A'), 
               text = ~paste('Representative:',Last.Name,
                             "Party:",party.labels))


fig
dev.off() #sets graphics back to default
```


  





